import { Injectable } from '@nestjs/common';
import { Alert } from '../../../entities/alert.entity';
import { NbPeer } from '../../../entities/nb-peer.entity';
import { NbGroup } from '../../../entities/nb-group.entity';

@Injectable()
export class EmailTemplates {
  static peerOffline(alert: Alert, peer: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Peer Offline Alert: ${peer.peerName}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">⚠️ ${peer.peerName} is Offline</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toString().toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Alert Details</h2>
          <p><strong>Peer Name:</strong> ${peer.peerName}</p>
          <p><strong>IP Address:</strong> ${peer.peerIp}</p>
          <p><strong>Location:</strong> ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}</p>
          <p><strong>Offline Duration:</strong> ${peer.offlineDuration}</p>
          <p><strong>Last Seen:</strong> ${peer.lastSeen || 'Never'}</p>
          <p><strong>Account ID:</strong> ${peer.accountId}</p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      Peer Offline Alert: ${peer.peerName}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Peer Name: ${peer.peerName}
      IP Address: ${peer.peerIp}
      Location: ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}
      Offline Duration: ${peer.offlineDuration}
      Last Seen: ${peer.lastSeen || 'Never'}
      Account ID: ${peer.accountId}
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }

  static peerFlapping(alert: Alert, peer: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Peer Flapping Alert: ${peer.peerName}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">🔄 ${peer.peerName} is Flapping</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Alert Details</h2>
          <p><strong>Peer Name:</strong> ${peer.peerName}</p>
          <p><strong>IP Address:</strong> ${peer.peerIp}</p>
          <p><strong>Current Status:</strong> ${peer.currentState}</p>
          <p><strong>State Changes:</strong> ${peer.stateChangeCount} in ${peer.periodMinutes} minutes</p>
          <p><strong>Location:</strong> ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}</p>
          <p><strong>Account ID:</strong> ${peer.accountId}</p>
        </div>
        <div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;">
          <p style="margin: 0; color: #856404;">
            <strong>⚠️ Action Required:</strong> This peer is experiencing frequent connectivity changes. Check the network infrastructure and peer configuration.
          </p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      Peer Flapping Alert: ${peer.peerName}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Peer Name: ${peer.peerName}
      IP Address: ${peer.peerIp}
      Current Status: ${peer.currentState}
      State Changes: ${peer.stateChangeCount} in ${peer.periodMinutes} minutes
      Location: ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}
      Account ID: ${peer.accountId}
      
      ⚠️ Action Required: This peer is experiencing frequent connectivity changes. Check the network infrastructure and peer configuration.
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }

  static newPeer(alert: Alert, peer: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>New Peer Detected: ${peer.peerName}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">🆕 New Peer Detected: ${peer.peerName}</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Peer Details</h2>
          <p><strong>Peer Name:</strong> ${peer.peerName}</p>
          <p><strong>IP Address:</strong> ${peer.peerIp}</p>
          <p><strong>Operating System:</strong> ${peer.os || 'Unknown'}</p>
          <p><strong>Version:</strong> ${peer.version || 'Unknown'}</p>
          <p><strong>Status:</strong> ${peer.status}</p>
          <p><strong>Desktop:</strong> ${peer.desktop ? 'Yes' : 'No'}</p>
          <p><strong>SSH Enabled:</strong> ${peer.sshEnabled ? 'Yes' : 'No'}</p>
          <p><strong>Location:</strong> ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}</p>
          <p><strong>First Seen:</strong> ${peer.firstSeenAt}</p>
          <p><strong>Account ID:</strong> ${peer.accountId}</p>
        </div>
        <div style="background-color: #d4edda; padding: 15px; border-left: 4px solid #28a745; margin: 20px 0;">
          <p style="margin: 0; color: #155724;">
            <strong>ℹ️ Security Note:</strong> Please verify that this new peer is authorized to join your network.
          </p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      New Peer Detected: ${peer.peerName}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Peer Name: ${peer.peerName}
      IP Address: ${peer.peerIp}
      Operating System: ${peer.os || 'Unknown'}
      Version: ${peer.version || 'Unknown'}
      Status: ${peer.status}
      Desktop: ${peer.desktop ? 'Yes' : 'No'}
      SSH Enabled: ${peer.sshEnabled ? 'Yes' : 'No'}
      Location: ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}
      First Seen: ${peer.firstSeenAt}
      Account ID: ${peer.accountId}
      
      ℹ️ Security Note: Please verify that this new peer is authorized to join your network.
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }

  static groupHealth(alert: Alert, group: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Group Health Alert: ${group.groupName}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">📊 Group Health Degraded: ${group.groupName}</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Group Statistics</h2>
          <p><strong>Group Name:</strong> ${group.groupName}</p>
          <p><strong>Total Peers:</strong> ${group.totalPeers}</p>
          <p><strong>Online Peers:</strong> ${group.onlinePeers}</p>
          <p><strong>Offline Peers:</strong> ${group.offlinePeers}</p>
          <p><strong>Online Rate:</strong> ${group.onlineRate}%</p>
          <p><strong>Required Threshold:</strong> ${group.threshold}%</p>
          <p><strong>Account ID:</strong> ${group.accountId}</p>
        </div>
        <div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;">
          <p style="margin: 0; color: #856404;">
            <strong>⚠️ Health Issue:</strong> Group online rate is below the required threshold. This may indicate network issues or widespread connectivity problems.
          </p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      Group Health Alert: ${group.groupName}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Group Name: ${group.groupName}
      Total Peers: ${group.totalPeers}
      Online Peers: ${group.onlinePeers}
      Offline Peers: ${group.offlinePeers}
      Online Rate: ${group.onlineRate}%
      Required Threshold: ${group.threshold}%
      Account ID: ${group.accountId}
      
      ⚠️ Health Issue: Group online rate is below the required threshold. This may indicate network issues or widespread connectivity problems.
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }

  static peerInactivity(alert: Alert, peer: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Peer Inactivity Alert: ${peer.peerName}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">💤 Peer Inactive: ${peer.peerName}</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Inactivity Details</h2>
          <p><strong>Peer Name:</strong> ${peer.peerName}</p>
          <p><strong>IP Address:</strong> ${peer.peerIp}</p>
          <p><strong>Days Inactive:</strong> ${peer.daysInactive}</p>
          <p><strong>Threshold:</strong> ${peer.thresholdDays} days</p>
          <p><strong>Last Seen:</strong> ${peer.lastSeen || 'Never'}</p>
          <p><strong>Total Uptime:</strong> ${peer.totalUptimeMinutes} minutes</p>
          <p><strong>Location:</strong> ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}</p>
          <p><strong>Account ID:</strong> ${peer.accountId}</p>
        </div>
        <div style="background-color: #d1ecf1; padding: 15px; border-left: 4px solid #17a2b8; margin: 20px 0;">
          <p style="margin: 0; color: #0c5460;">
            <strong>💡 Recommendation:</strong> Consider removing this stale peer or check if it's still needed in your network.
          </p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      Peer Inactivity Alert: ${peer.peerName}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Peer Name: ${peer.peerName}
      IP Address: ${peer.peerIp}
      Days Inactive: ${peer.daysInactive}
      Threshold: ${peer.thresholdDays} days
      Last Seen: ${peer.lastSeen || 'Never'}
      Total Uptime: ${peer.totalUptimeMinutes} minutes
      Location: ${peer.locationCity || 'Unknown'}, ${peer.locationCountry || 'Unknown'}
      Account ID: ${peer.accountId}
      
      💡 Recommendation: Consider removing this stale peer or check if it's still needed in your network.
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }

  static networkChange(alert: Alert, changeData: any): { html: string; text: string } {
    const severityColor = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      critical: '#dc3545',
    };

    const changeIcon = {
      increase: '📈',
      decrease: '📉',
      improved: '✅',
      degraded: '❌',
    };

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Network Change Alert: ${changeData.metric}</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background-color: ${severityColor[alert.severity]}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">${changeIcon[alert.description.split(' ')[0] as keyof typeof changeIcon] || '🔔'} Network Change Detected</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Severity: ${alert.severity.toUpperCase()}</p>
        </div>
        <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
          <h2 style="color: #495057; margin-top: 0;">Change Details</h2>
          <p><strong>Metric:</strong> ${changeData.metric}</p>
          <p><strong>Previous Value:</strong> ${changeData.previousValue}</p>
          <p><strong>Current Value:</strong> ${changeData.currentValue}</p>
          <p><strong>Change:</strong> ${changeData.changePercentage > 0 ? '+' : ''}${changeData.changePercentage}%</p>
          <p><strong>Threshold:</strong> ${changeData.threshold}%</p>
          <p><strong>Account ID:</strong> ${changeData.accountId}</p>
        </div>
        <div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;">
          <p style="margin: 0; color: #856404;">
            ${alert.description}
          </p>
        </div>
        <div style="background-color: #e9ecef; padding: 15px; text-align: center; border-radius: 0 0 5px 5px;">
          <p style="margin: 0; font-size: 14px; color: #6c757d;">
            This alert was generated by the NetBird Management Platform.
          </p>
        </div>
      </body>
      </html>
    `;

    const text = `
      Network Change Alert: ${changeData.metric}
      
      Severity: ${alert.severity.toUpperCase()}
      
      Metric: ${changeData.metric}
      Previous Value: ${changeData.previousValue}
      Current Value: ${changeData.currentValue}
      Change: ${changeData.changePercentage > 0 ? '+' : ''}${changeData.changePercentage}%
      Threshold: ${changeData.threshold}%
      Account ID: ${changeData.accountId}
      
      ${alert.description}
      
      ---
      This alert was generated by the NetBird Management Platform.
    `;

    return { html, text };
  }
}